# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /donaldwu.github.com
  Archives: /donaldwu.github.com/archives/index.html
  About: /donaldwu.github.com/about/darrenwu.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/Deirenwu
github_url: https://github.com/klugjo/hexo-theme-alpha-dust
email_url: deirenwu1101@gmail.com
rss_url: \#

# Footer About Text
footer_about: "This theme was developed by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>. The source code is available on Github. Create Websites. Make Magic."

# Footer Copyright Line
footer_copyright: "@Untitled. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

